name: Dispatch work flow
on:
  workflow_dispatch
jobs:
  job1:
    runs-on: Windows
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: |
             $GITHUB_OUTPUT=$(echo "test=hello")
             echo $GITHUB_OUTPUT
  job2:
    runs-on: Windows
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1 $OUTPUT2"
    
