name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
     - name: Build
       run: |
            git config user.name "mohamed hassan"
            git config user.email mohamed.hassan@thirdwayv.com
            echo "Build new binaries"
            .\commit.bat 
            echo ${{github.head_ref}}
            echo ${{github.ref_name}}
            echo ${{github.base_ref}}
            echo ${{github.path}}
            echo ${{github.actor}}
            echo ${{github.actor_id}}
            git push origin ${{github.base_ref}}
    
    
