name: Dispatch work flow
on:
  workflow_dispatch

jobs:
  job1:
    runs-on: 	
      - self-hosted
      - Windows
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{github.token}}      
     - run: |
             echo "Build new binaries"
             ls
             ./commit.bat 
             git commit ./README.md -m " new commit"
             git push
