name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{github.token}}

     - name: Delete_Branch
       run: |
             git branch -D Develop-Auto-Build
             git push origin --delete Develop-Auto-Build

     - name: Create_Branch
       run: |
             git switch -c Develop-Auto-Build
     - name: Auto Build
       run: |
             echo "Auto build started"
             .\commit.bat
     - name: Create_PR
       run: |
             gh pr create --base PLAT-14384_1 --head Develop-Auto-Build
     - name: Merge_PR
       run: |
             gh pr merge Develop-Auto-Build --delete-branch
    
    
