name: Atlas Auto Build
on:
  pull_request_review:
    types:
      - submitted
jobs:
  if_approved:
    if: github.event.review.state == 'approved'
    
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{ secrets.TEST_SECRET }}
      - name: Build
        run: |
             $states = @()
             $states=$(gh pr view ${{ github.event.pull_request.number }} --json latestReviews --jq .[].[].state)
             Write-Output $states.count
             $approvesCount = 0
             foreach($state in $states)
             {
               Write-Output $state
               if($state -eq "APPROVED")
               {
                 $approvesCount++
               }
             }
             if($approvesCount -eq 3)
             {
               echo "Run Auto Build"
             }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
