name: Dispatch work flow
on:
  workflow_dispatch
jobs:
  Dispatch:
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
     - name: Auto Build
       run: |
            echo ${{ github.action }}
            echo ${{ github.action_path }}
            echo ${{ github.action_ref }}
            echo ${{ github.action_repository }}
            echo ${{ github.action_status }}
            echo ${{ github.actor }}
            echo ${{ github.actor_id }}
            echo ${{ github.api_url }}
            echo ${{ github.base_ref }}
            echo ${{ github.env }}
            echo ${{ github.event }}
            echo ${{ github.event_name }}
            echo ${{ github.event_path }}
            echo ${{ github.graphql_url }}
            echo ${{ github.head_ref }}
            echo ${{ github.job }}
            echo ${{ github.job_workflow_sha }}
            echo ${{ github.path }}
            echo ${{ github.ref }}
            echo ${{ github.ref_name }}
            echo ${{ github.ref_protected }}
            echo ${{ github.ref_type }}
            echo ${{ github.repository }}
            echo ${{ github.repository_id }}
            echo ${{ github.repository_owner }}
            echo ${{ github.repository_owner_id }}
            echo ${{ github.repositoryUrl }}
            echo ${{ github.retention_days }}
            echo ${{ github.run_attempt }}
            echo ${{ github.run_id }}
            echo ${{ github.run_number }}
            echo ${{ github.secret_source }}
            echo ${{ github.server_url }}
            echo ${{ github.sha }}
            echo ${{ github.token }}
            echo ${{ github.triggering_actor }}
            echo ${{ github.workflow }}
            echo ${{ github.workflow_ref }}
            echo ${{ github.workflow_sha }}
            echo ${{ github.workspace }}
            echo "auto build"
    
    
