name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{github.token}}

     - name: Delete_Branch
       run: |            
            $check_local_branch = $(git branch --list Develop-Auto-Build)
            echo $check_local_branch
            if($check_local_branch -ne "Develop-Auto-Build")
            {
              git branch -D Develop-Auto-Build
            }

     - name: Create_Branch
       run: |
             git switch -f -c Develop-Auto-Build
     - name: Auto Build
       run: |
             echo "Auto build started"
             .\commit.bat
             git commit *.txt Auto build passed"
             git.exe push --force
     - name: Create_PR
       run: |
             gh pr create --base main --head Develop-Auto-Build
     - name: Merge_PR
       run: |
             gh pr merge Develop-Auto-Build --delete-branch
    
    
