name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{github.token}}
     - name: Build
       run: |
            echo "Build new binaries"
            .\commit.bat 
             git commit *.md -m "Auto build passed"
             echo ${{github.base_ref}}
             git push origin ${{github.base_ref}}
       env: 
        GIHUB_TOKEN: ${{github.token}}
    
