name: Atlas Auto Build
on:
  pull_request_review_comment:
    types:
      - created
jobs:
  if_approved:
    #if: github.event.review.state == 'approved'
    if: github.event.comment.body == 'run auto build'
    runs-on: 	
      - self-hosted
      - Windows
      - test
    env: 
      AUTHOR_NAME: ${{github.actor}}
    steps:
     # - uses: actions/checkout@v4
       # with:
          # clean: true
          # fetch-depth: '0'
          # submodules: 'true'
     - name: Build
       run: |
            echo ${{github.event.pull_request.state }}
            echo "Auto build started"
            #Add code to run auto-build
    
    
