name: Dispatch work flow
on:
  workflow_dispatch
env:
  shell: bash
jobs:
  job1:
    runs-on: Windows
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: |
             echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: Windows
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: |
             echo "$OUTPUT1"
             echo ${{needs.job1.outputs.output1}}
    
