name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: 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
     - name: Build
       run: |
            echo "Build new binaries"
            .\commit.bat 
    
    
