name: Atlas Auto Build
on:
  pull_request_review:
    types:
      - submitted
jobs:
  if_approved:
    if: github.event.review.state == 'approved'
    
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
     # - uses: actions/checkout@v4
       # with:
          # clean: true
          # fetch-depth: '0'
          # submodules: 'true'
     - name: Build
       run: |
            echo ${{ github.run_attempt }}
            echo ${{ github.run_id }}
            echo ${{ github.run_number }}
            echo ${{ github.event.pull_request.number }}
            gh pr view ${{ github.event.pull_request.number }}
            gh pr view ${{ github.event.pull_request.number }} --json latestReviews
            gh pr view ${{ github.event.pull_request.number }} --json Reviews
            gh pr view ${{ github.event.pull_request.number }} --json reviewDecision

            echo "Auto build started"
            #Add code to run auto-build
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
