name: Atlas Project Binaries
run-name: Building Atlas Project Binaries
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: 	
      - self-hosted
      - Windows
      - test
    env:
      AUTHOR_NAME: ${{github.actor}}
    steps:
     - uses: actions/checkout@v4
       with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: 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  
     - name: Build
       run: |
            echo "Build new binaries"
            .\commit.bat 
    
    
