name: Atlas Auto Build
on:
  pull_request:
    types:
      #run the job when pull request opened
      - opened
  pull_request_review:
    types:
      - submitted
jobs:
  if_approved:
    if: (github.event.review.state == 'approved') && (github.actor != 'twi-general')
    
    runs-on: 	
      - self-hosted
      - Windows
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: '0'
          submodules: 'true'
          token: ${{ secrets.TEST_SECRET }}
      - name: Build
        run: |
             $ReviewStates = @()
             $ReviewStates=$(gh pr view ${{ github.event.pull_request.number }} --json latestReviews --jq .[].[].state)

             $approvesCount = 0

             foreach($state in $ReviewStates)
             {
               if($state -eq "APPROVED")
               {
                 $approvesCount++
               }
             }

             if($approvesCount -eq 1)
             {
               echo "Auto build started"
             }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Tools_Build:
    if: github.actor != 'twi-general'
    runs-on: 	
      - self-hosted
      - Windows
    steps:
      - name: Echo
        run: |
             echo "Hello"
    
    
