name: Scheduler
on:
  schedule:
    - cron: '* * * * *'
jobs:
  scheduled_run:    
    runs-on: 	
      - ubuntu
    steps:
      - name: Build
        run: |
             echo "scheduled action"

    
    
