name: Scheduler
on:
  schedule:
    - cron: '55 * * * *'
jobs:
  scheduled_run:    
    runs-on: 	
      - self-hosted
      - Windows
      - test
    steps:
      - name: Build
        run: |
             echo "scheduled action"

    
    
